### ISSUE TITLE
Locked and collapsed tabs steal tabs when moving tabs using ctrl-shift-pageup and ctrl-shift-pagedown

### ISSUE THREAD

**Issue by Gert-dev** [piroor/tst-lock-tree-collapsed#10]
You can move tabs around using `ctrl-shift-pageup` and `ctrl-shift-pagedown` in Firefox, which works fine in Tree Style Tabs as well. However, if tabs are locked and collapsed, they seem to "steal" tabs, i.e. with the following tabs:

* A - normal
* B - locked and collapsed
    * B2 - invisible due to parent being locked and collapsed
* C - normal

... using `ctrl-shift-pagedown` when `A` is active moves `A` inside `B`. What's worse: `B` doesn't expand and has "absorbed" the tab. You also lose focus on `A` because Tree Style Tabs wants to remove focus from invisible tabs, which it now is. The same happens when using `ctrl-shift-pageup` and `C` is active.

The expected behavior would probably be for `A` to be moved above `C` and below `B` on `ctrl-shift-pagedown`, and `C` to be moved below `A` and above `B` on `ctrl-shift-pageup`, i.e. these shortcuts should skip invisible tabs, just like `ctrl-tab` and `ctrl-shift-tab` do.

Thanks!

**Comment by piroor** [comment]
I've implemented a safe guard for such a situation. But it may work accidentally even if the tab-move is produced by drag and drop.

And I've seen another problem of TST itself while testing: https://github.com/piroor/treestyletab/issues/2556

**Comment by piroor** [comment]
> But it may work accidentally even if the tab-move is produced by drag and drop.

I think such a case can be ignored, because the result of such an operation in the horizontal tab bar is already complicated. And drag-and-drop on the sidebar won't produce such a result because tabs attached to a collapsed tree will be attached as the last child of the drop target - the result is different from Ctrl-Shift-PageUp/PageDown.

So I think this issue is now fixed.

**Comment by Gert-dev** [comment]
Thanks for your response. I can confirm this is _mostly_ fixed (it's certainly improved :smile: !);  I can't reproduce this consistently, but sometimes a collapsed tree still "steals" or "swallows" the tab.

Perhaps the same issue or a related one happens if I very quickly press `ctrl-shift-pagedown` multiple times when my tab is just above a locked and collapsed tab. In that case the skipping doesn't appear to work, perhaps because the tab hasn't had a chance to "correct" itself by moving outside of it again.

**Comment by piroor** [comment]
You are right, the current implementation is fragile...

I've done more changes with a newly introduced API to TST. I hope they work more robustly on such cases.

**Comment by Gert-dev** [comment]
I can't reproduce the problem anymore with the latest release. It sometimes takes some time for the tab to move itself (perhaps if the collapsed tree is large), but it finally moves to the correct location, which is the most important thing. Thanks!
