### ISSUE TITLE
[Feature request] Lock as expanded

### ISSUE THREAD

**Issue by SHHSSH** [piroor/tst-lock-tree-collapsed#24]
Hi @piroor 

Hope your year is going well mate.
I am inquiring if at all possible for the functionality of "Lock as expanded" to be added into LAC.
This can be really useful for this who macro to their hotkeys "Collapse all" just as lock as collapsed if really useful for those who use "Expand all".

This is more noticeable to me everyday when I have many trees and am primarily focusing on a few and have to go back to expand them manually.

If this is at all a possibility in the future, it would be much appreciated by many I'm sure.

Thanks sir,
Be well.

**Comment by piroor** [comment]
I've implemented those options with the commit b64eb5e.
It depends on new API introduced at TST 3.9.17 and later. I'll update this addon after TST 3.9.17 is released.
https://github.com/piroor/treestyletab/wiki/API-for-other-addons#suppress-unintentional-collapsion-of-expanded-tree-by-tst

**Comment by SHHSSH** [comment]
Here I am trying to configure it without 3.9.17 being released!

Thanks so much @piroor -really appreciate you making the effort to implement this.
