### ISSUE TITLE
Important usage parameters

### ISSUE THREAD

**Issue by SHHSSH** [piroor/tst-lock-tree-collapsed#4]
I was using lock as collapsed for quite sometime and there are few parameters users need to set prior to it functioning in a reasonable state.

This is just a recap of a few trial and errors I ran through in the setup/adjustment of LAC.

<a href='https://postimg.cc/mzGqJfxL' target='_blank'><img src='https://i.postimg.cc/mzGqJfxL/capture-013-08032020-030146.jpg' border='0' alt='capture-013-08032020-030146'/></a>
^ This will allow you to prevent opening child tabs of a locked group.

However, when working with multiple groups that are inbetween your other tabs/groups this becomes problematic (slightly). The problem arises when you attempt to Ctrl+Tab PAST the LAC group. TST becomes stuck attempting to tab to the next parent or independent tab. Backtracking with Ctrl+Shift+Tab however, does bypass the LAC group and intuitively take you to the previous parent or independent tab

A simple circumvention of this is to just throw your LAC groups to the bottom so you don't have to deal with the Ctrl+Tab function becoming stuck on the LAC group.

But as a final issue/request for this add-on I would really appreciate if you could see if you could figure out a workaround for this @piroor 

Gif representation: 
<a href="https://gifyu.com/image/Icod"><img src="https://s5.gifyu.com/images/LACerror.gif" alt="LACerror.gif" border="0" /></a>

^ This is just me Ctrl+Tabbing to show you how it gets stuck only for Ctrl+Tab and not Ctrl+Shift+Tab.

Is there anyway you can forcefully have it jump past LAC groups onto the next parent or independent tab?

Thanks bro, as always, love your work.

P.S

Hotkeys still override LAC's function, i.e; {F2} & {F4} (I think these are the defaults, if not sorry I changed mine)

So obviously F2 doesn't mean anything as it's collapsing the groups, but with F4 it will still forcefully expand LAC groups. (This isn't a priority, I don't use the hotkeys that often)

**Comment by SHHSSH** [comment]
Also there are multiple (3) Lock as collapsed buttons in the context menu in separate areas. I don't know if this was intended or not, once again, not a big problem and I'm just informing you :)

[url=https://gifyu.com/image/IcAZ][img]https://s5.gifyu.com/images/capture_014_08032020_035530.jpg[/img][/url]

**Comment by piroor** [comment]
> TST becomes stuck attempting to tab to the next parent or independent tab. Backtracking with Ctrl+Shift+Tab however, does bypass the LAC group and intuitively take you to the previous parent or independent tab

I've confirmed this, and there is a workaround: TST Options => "Tree Behavior" => turn "Don'T expand collapsed tree and skip collapsed descendants..." checked.

**Comment by piroor** [comment]
> Hotkeys still override LAC's function, i.e; {F2} & {F4} (I think these are the defaults, if not sorry I changed mine)
> 
> So obviously F2 doesn't mean anything as it's collapsing the groups, but with F4 it will still forcefully expand LAC groups. (This isn't a priority, I don't use the hotkeys that often)

F2 is assigned to "Toggle Sub Panel" by default, and F4 is free. It looks F2 was assigned to "Focus to Previous Tab" or some other commands. Could you list all shortcuts customized for TST? (You can see them at about:addons => the gear button => Manage Extension Shortcuts.

**Comment by piroor** [comment]
The first problem https://github.com/piroor/tst-lock-tree-collapsed/issues/4#issuecomment-596138761 should be fixed by https://github.com/piroor/tst-lock-tree-collapsed/commit/816f4a604aac0374e898eaf24780e5909cbdb2a8 and https://github.com/piroor/treestyletab/commit/75d643b2c604eeec38c59d44ddbe0432d77713d5

**Comment by piroor** [comment]
I've uploaded TST 3.4.4 and TST Lock Tree Collapsed 1.0.1 with these fixes.

**Comment by SHHSSH** [comment]
<a href="https://gifyu.com/image/Icod"><img src="https://gifyu.com/image/I6RQ" alt="LACerror.gif" border="0" /></a>

<a href="https://gifyu.com/image/Icod"><img src="https://gifyu.com/image/I6RW" alt="LACerror.gif" border="0" /></a>


<a href="https://gifyu.com/image/Icod"><img src="https://gifyu.com/image/I6Ru" alt="LACerror.gif" border="0" /></a>
^ This was a temporary work around I was using when LAC was just being added. It allowed me to somehow skip the locked tree instead of using Ctrl+Tab/ShiftTab.

**Comment by SHHSSH** [comment]
> 
> 
> > TST becomes stuck attempting to tab to the next parent or independent tab. Backtracking with Ctrl+Shift+Tab however, does bypass the LAC group and intuitively take you to the previous parent or independent tab
> 
> I've confirmed this, and there is a workaround: TST Options => "Tree Behavior" => turn "Don't expand collapsed tree and skip collapsed descendants..." checked.

Ok I confirm this does work. 
![capture_026_08032020_185939](https://user-images.githubusercontent.com/21285581/76159721-fd2b6d80-616e-11ea-8fe8-6f1e422bb156.jpg)

However, you must have ALL 3 LAC context menu options selected, otherwise it malfunctions.

![capture_030_08032020_190300](https://user-images.githubusercontent.com/21285581/76159780-85aa0e00-616f-11ea-965d-4689872a62f0.jpg)

**Comment by SHHSSH** [comment]
I'd say this issue is fixed, just look at the excess context menu options for LAC piroor :) 

Cheers, thanks.

**Comment by piroor** [comment]
> However, you must have ALL 3 LAC context menu options selected, otherwise it malfunctions.

I cannot see this problem. I've removed these items from TST itself, and completely unexpected state on TST 3.4.0 and later...

**Comment by SHHSSH** [comment]
Yeah all good, those extra context menus have gone when I updated.
