### ISSUE TITLE
Cannot use ctrl-shift-tab to go to previous tab when current tab is first tab and last tab is a collapsed and locked tab

### ISSUE THREAD

**Issue by Gert-dev** [piroor/tst-lock-tree-collapsed#9]
If the last tab in the tree is locked and collapsed (i.e. with one tab under it) and the very first tab - which is another tab - is active, `ctrl-shift-tab` does not go back to the previous tab, i.e. the locked and collapsed tab itself.

The screen does seem to flicker for a moment, as if the extension is _trying_ to go to the previous tab and then deciding against it and going back to the tab you were. Maybe there is some wrapping/clamping code that isn't working as intended.

Going from the last, collapsed and locked, tab to the first tab using `ctrl-tab` works fine. Navigating between other tabs using `ctrl-shift-tab` also works fine, including if the last tab is not a collapsed and locked tab. This seems to be a corner case.

Thanks for this great plugin!

**Comment by piroor** [comment]
Thanks, this was due to TST's bug and it has been fixed with the commit https://github.com/piroor/treestyletab/commit/80b197bdb159e3c39838eb08392ffd5ab0ac790d.

**Comment by Gert-dev** [comment]
I can confirm this is fixed, thanks!
